### ISSUE TITLE
Resolve StacksProvider conflict across wallets

### ISSUE THREAD

**Issue by markmhendrickson** [hirosystems/connect#325] opened 2023-07-17 13:57 UTC
Currently wallets that use `StacksProvider` such as Hiro and Xverse experience collisions whenever both are installed and using apps that have integrated Connect since the library doesn't have a way to distinguish between each wallet when the user wants to perform actions with them (e.g. connect, transact).

Developers and users alike would benefit from having the library distinguish them somehow so that only the wallet of choice is incurred for the particular app session, even if multiple remain installed and activated.

Hiro exposes `HiroWalletProvider` as well which may be helpful for supporting such an enhancement.

<img width="422" alt="Screenshot 2023-07-17 at 15 55 48" src="https://github.com/hirosystems/connect/assets/28991/33d16cef-eee3-45a7-b8e9-67fbbf8be9e4">

**Comment by janniks** [comment] 2023-07-17 13:59
💯

I'd like to see Connect try to implement a `.providers` array, where wallets can register their named providers. (something similar has been discussed in a working group)

**Comment by Anatolie** [comment] 2023-07-17 15:38
+1! Would like to be able to trigger a specific wallet extension (ie: Hiro) when performing actions such as PSBT + message signing!

**Comment by janniks** [comment] 2023-07-17 15:46
I think we could add a quick fix to allow web devs to target a specific wallet using connect. Basically let most functions take in the provider directly, rather than guessing/taking the main one

**Comment by janniks** [comment] 2023-07-18 09:56
1st pass to allow web apps to pass a known stacks provider (up to them to select the one they want etc.) #326

**Comment by RobertClarke** [comment] 2023-07-20 07:07
Reproducible across all the major Ordinals Marketplaces!

**Comment by markmhx** [comment] 2023-07-20 08:26
@RobertClarke Might your team want to try integrating the branch here to confirm it works on your end pre-release? https://github.com/hirosystems/connect/pull/326

**Comment by janniks** [comment] 2023-07-27 17:10
Reopening this for further improvements. The first pass fixed #320

**Comment by markmhx** [comment] 2023-07-28 10:28
Curious which improvements you have in mind, and whether we should hold off asking developers to upgrade their integrations or is that effort good to go with the first pass?

**Comment by janniks** [comment] 2023-07-28 16:02
Would like to test out a .provider interface where wallets register their presence and connect would use it to allow users to select their choice and route requests to the custom provider. 
But for now I'd recommend going with what we have already, since it might take a while for wallets to adopt any new experiments.

**Comment by ThomAille** [comment] 2023-08-23 16:23
I am implementing Stack/Connect to allow my users to connect either with Hiro or Xverse, to avoid the integration of several libraries, I only use this one.

For once Hiro it's easy I push HiroWalletProvider in showConnect on the other hand for xverse I have explored windows in vain I can't find a specific provider for it. For once, send you what as info for xverse?

**Comment by dawasherpa-ui** [comment] 2023-09-23 04:01
> cc @m-aboelenein is Xverse thinking about adding a similar custom provider? Maybe we should discuss this in the wallet api standards group?
in the authOptions what the provider name of xverseWallet?

**Comment by janniks** [comment] 2023-09-25 17:05
@fess-v feel free to leave you ideas here as well. Curious to hear all sides 🙂

**Comment by m-aboelenein** [comment] 2023-09-26 23:25
> I am implementing Stack/Connect to allow my users to connect either with Hiro or Xverse, to avoid the integration of several libraries, I only use this one.
> 
> For once Hiro it's easy I push HiroWalletProvider in showConnect on the other hand for xverse I have explored windows in vain I can't find a specific provider for it. For once, send you what as info for xverse?

Hello @ThomAille in the latest version of xverse we have added a custom provider you can find it under `window.XverseProviders.StacksProvider`

**Comment by janniks** [comment] 2023-12-04 16:40
Closed by #341

**Closed by janniks** 2023-12-04 16:40 UTC
